### ISSUE TITLE
[Bug]: Can't build from source?

### ISSUE THREAD

**Issue by Fiddydoo1** [vzhd1701/gridplayer#263]
### GridPlayer version

Version that's used when doing git clone of the repo

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

I wanted to create a modified version of this repo by trying to build it from source.

Python version 3.13.3
pip version 25.0.1
Installed pipx like this:
python -m pip install --user pipx.
Installed poetry like this:
pipx install poetry
in windows command prompt: poetry install --no-dev
results in:
Creating virtualenv gridplayer-jxB52Mnx-py3.13 in C:\Users\Kompyuter\AppData\Local\pypoetry\Cache\virtualenvs

The option "--no-dev" does not exist

When trying to do "poetry install --no-dev" I get an error saying that no option called --no-dev exists. And reading the documentation for poetry on their website it says that that command has been deprecated and that you should use --without dev or --only main instead.  https://python-poetry.org/docs/1.8/cli/

Using --without dev gives an error saying PEP517 build of a dependency failed

I also got similar errors when trying to build it in arch linux.

I appreciate any help!

### Log excerpt

```shell
poetry install --without dev
Installing dependencies from lock file

Package operations: 35 installs, 0 updates, 0 removals

  - Installing attrs (21.4.0)
  - Installing pycparser (2.21)
  - Installing cffi (1.16.0): Failed

PEP517 build of a dependency failed

Backend subprocess exited when trying to invoke build_wheel

    | Command '['C:\\Users\\KOMPYU~1\\AppData\\Local\\Temp\\tmp_zt8z_jf\\.venv\\Scripts\\python.exe', 'C:\\Users\\Kompyuter\\pipx\\venvs\\poetry\\Lib\\site-packages\\pyproject_hooks\\_in_process\\_in_process.py', 'build_wheel', 'C:\\Users\\KOMPYU~1\\AppData\\Local\\Temp\\tmpxqucxeys']' returned non-zero exit status 1.
    |
    | _configtest.c
    | C:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\Lib\site-packages\setuptools\dist.py:761: SetuptoolsDeprecationWarning: License classifiers are deprecated.
    | !!
    |
    |         ********************************************************************************
    |         Please consider removing the following classifiers in favor of a SPDX license expression:
    |
    |         License :: OSI Approved :: MIT License
    |
    |         See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
    |         ********************************************************************************
    |
    | !!
    |   self._finalize_license_expression()
    | running bdist_wheel
    | running build
    | running build_py
    | creating build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\api.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\backend_ctypes.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\cffi_opcode.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\commontypes.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\cparser.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\error.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\ffiplatform.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\lock.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\model.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\pkgconfig.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\recompiler.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\setuptools_ext.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\vengine_cpy.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\vengine_gen.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\verifier.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\_imp_emulation.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\_shimmed_dist_utils.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\__init__.py -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\_cffi_include.h -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\parse_c_type.h -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\_embedding.h -> build\lib.win-amd64-cpython-313\cffi
    | copying src\cffi\_cffi_errors.h -> build\lib.win-amd64-cpython-313\cffi
    | running build_ext
    | building '_cffi_backend' extension
    | creating build\temp.win-amd64-cpython-313\Release\src\c
    | creating build\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64
    | "Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DFFI_BUILDING=1 -Isrc/c/libffi_x86_x64 -IC:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\Include "-IZ:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\include" "-IZ:\Visual Studio build tools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/c/_cffi_backend.c /Fobuild\temp.win-amd64-cpython-313\Release\src\c\_cffi_backend.obj
    | _cffi_backend.c
    | src/c/_cffi_backend.c(413): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(414): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1105): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1114): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1139): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1162): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1181): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1195): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1344): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1346): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1696): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1697): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1699): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1711): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1712): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1715): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1734): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1778): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1843): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1845): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1856): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(1859): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(2258): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(2263): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(2267): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(2282): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(2341): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(3271): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(3992): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4092): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4208): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4249): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4521): warning C4133: 'function': incompatible types - from 'PyUnicodeObject *' to 'PyObject *'
    | src/c/_cffi_backend.c(4532): warning C4996: 'Py_FileSystemDefaultEncoding': deprecated in 3.12
    | src/c/_cffi_backend.c(4816): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4834): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4975): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4966): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(4987): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5383): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5430): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5437): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5656): warning C4244: '=': conversion from 'Py_ssize_t' to 'unsigned short', possible loss of data
    | src/c/_cffi_backend.c(5790): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5794): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5810): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5823): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5852): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | src/c/_cffi_backend.c(5918): warning C4244: 'function': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
    | src/c/_cffi_backend.c(6006): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
    | src/c/_cffi_backend.c(6121): warning C4013: '_PyErr_WriteUnraisableMsg' undefined; assuming extern returning int
    | src/c/_cffi_backend.c(6556): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\parse_c_type.c(218): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\parse_c_type.c(287): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\parse_c_type.c(341): warning C4244: '=': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\parse_c_type.c(445): warning C4244: 'return': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(425): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(430): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(448): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(460): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(559): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(621): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(700): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\realize_c_type.c(753): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(130): warning C4244: 'initializing': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(306): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(358): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(384): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(405): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\lib_obj.c(419): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(170): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(215): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(247): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(248): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(260): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(261): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(281): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(301): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(302): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(307): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(327): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\cdlopen.c(331): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    | C:\Users\Kompyuter\AppData\Local\Temp\tmp430akrta\cffi-1.16.0\src\c\call_python.c(110): warning C4244: 'function': conversion from 'intptr_t' to 'int', possible loss of data
    | "Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DFFI_BUILDING=1 -Isrc/c/libffi_x86_x64 -IC:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\Include "-IZ:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\include" "-IZ:\Visual Studio build tools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/c/libffi_x86_x64\ffi.c /Fobuild\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\ffi.obj
    | ffi.c
    | "Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DFFI_BUILDING=1 -Isrc/c/libffi_x86_x64 -IC:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\Include "-IZ:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\include" "-IZ:\Visual Studio build tools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/c/libffi_x86_x64\prep_cif.c /Fobuild\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\prep_cif.obj
    | prep_cif.c
    | src/c/libffi_x86_x64\prep_cif.c(169): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
    | "Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DFFI_BUILDING=1 -Isrc/c/libffi_x86_x64 -IC:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\include -IC:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\Include "-IZ:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\include" "-IZ:\Visual Studio build tools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/c/libffi_x86_x64\types.c /Fobuild\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\types.obj
    | types.c
    | "Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\libs /LIBPATH:C:\Users\Kompyuter\AppData\Local\Programs\Python\Python313\libs /LIBPATH:C:\Users\Kompyuter\AppData\Local\Programs\Python\Python313 /LIBPATH:C:\Users\KOMPYU~1\AppData\Local\Temp\tmp_zt8z_jf\.venv\PCbuild\amd64 "/LIBPATH:Z:\Visual Studio build tools\VC\Tools\MSVC\14.43.34808\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /EXPORT:PyInit__cffi_backend build\temp.win-amd64-cpython-313\Release\src\c\_cffi_backend.obj build\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\ffi.obj build\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\prep_cif.obj build\temp.win-amd64-cpython-313\Release\src\c\libffi_x86_x64\types.obj /OUT:build\lib.win-amd64-cpython-313\_cffi_backend.cp313-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-313\Release\src\c\_cffi_backend.cp313-win_amd64.lib src/c/libffi_x86_x64\win64.obj
    |    Creating library build\temp.win-amd64-cpython-313\Release\src\c\_cffi_backend.cp313-win_amd64.lib and object build\temp.win-amd64-cpython-313\Release\src\c\_cffi_backend.cp313-win_amd64.exp
    | _cffi_backend.obj : error LNK2001: unresolved external symbol _PyErr_WriteUnraisableMsg
    | build\lib.win-amd64-cpython-313\_cffi_backend.cp313-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
    | error: command 'Z:\\Visual Studio build tools\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

Note: This error originates from the build backend, and is likely not a problem with poetry but one of the following issues with cffi (1.16.0)

  - not supporting PEP 517 builds
  - not specifying PEP 517 build requirements correctly
  - the build requirements are incompatible with your operating system or Python version
  - the build requirements are missing system dependencies (eg: compilers, libraries, headers).

You can verify this by running pip wheel --no-cache-dir --use-pep517 "cffi (==1.16.0)".

  - Installing h11 (0.14.0)
  - Installing idna (3.4)
  - Installing outcome (1.2.0)
  - Installing sniffio (1.3.0)
  - Installing sortedcontainers (2.4.0)
```

**Comment by RIOplbLcDUxAUYIrJ** [comment]
Fork it, make changes and updates. Use github actions to build it since it's already set up

**Comment by LiberiFatali** [comment]
As I see it, this repository hasn't been updated to support Python 3.13. It works with Python 3.9 and 3.10.

**Comment by LiberiFatali** [comment]
This works with Python 3.13 now.
